### ISSUE TITLE
roadmap for initial release

### ISSUE THREAD

**Issue by vivekmalneedi** [vivekmalneedi/veridian#90]
## cross-platform builds
- [ ] add build for windows
- [ ] add build for mac
- [ ] build verible's tools as libraries

## vscode extension
- [ ] download veridian if not installed
- [ ] add end to end tests

## veridian
- [ ] add tests for all supported definitions
- [ ] use threadpool instead of individual threads for running the parser
